---
title: "Generating SPC charts with QCC and PostgreSQL"
author: "Matt Litz"
date: "2022-10-29"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(qcc)
library(RPostgreSQL)
library(tidyverse)
library(DBI)

```

## SPC with QCC 3.0



```{r posgresql_connect}

pw <- "at8&6ER8"
drv <- dbDriver("PostgreSQL")

con <- dbConnect(drv, 
                 dbname = "dvd_rental",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = pw)

dbExistsTable(con, "payment")

#Changed all METHODs in pg_hba.conf to trust & restart postgres
#Changed password-encryption in postgresql.conf to md5 & restart postgres
#Reset password for user postgres (which might have been redundant due to "method/trust") & restart postgres ...and it works.


```

## Query the PostgreSQL database


```{r posgresql_connect}
# query the data from postgreSQL 
df <- dbGetQuery(con, "SELECT * FROM payment WHERE customer_id =341 OR customer_id =532")

```



```{r head_df, echo=FALSE}
head(df)

```




```{r spc}

q1 <- qcc(df$amount, 
           type = "xbar.one",
          limits = c(2.5,7.5))
plot(q1)


```


```{r spc_rules}

df$RuleViol <- qccRules(q1)
df_rules <- na.omit(df)


```




```{r process_capability}

pc = processCapability(q1, spec.limits = c(3,5))
plot(pc)

```


```{r shiny_dashboard}
library(shiny)
library(shinydashboard)

ui <- dashboardPage(skin = "black",
  dashboardHeader(title = "Dept. SPC Charts", titleWidth = 200),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Charts", tabName = "charts", icon = icon("chart-simple"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "dashboard",
    # Boxes need to be put in a row (or column)
    fluidRow(
      column(width=10,
      box(plotOutput("plot1", width = NULL,height = 400)),
      box(plotOutput("plot2", width = NULL,height = 400))
      
      
      ),
      
      column(width=10,
      box(tableOutput('table'))
      
      )

    )),
    
    
      tabItem(tabName = "charts",)
  
    
  )
  )
)

server <- function(input, output) {
  set.seed(122)


  output$plot1 <- renderPlot({
    q1 <- qcc(df$amount, 
           type = "xbar.one",
          limits = c(2.5,7.5))
    plot(q1)
  })
  
  output$plot2 <- renderPlot({
    pc = processCapability(q1, spec.limits = c(3,5))
    plot(pc)
  })  
  
  output$table <- renderTable(df_rules)
  
  
}

shinyApp(ui, server)

#runApp(host = "0.0.0.0", port = 5050)

```








